### ISSUE TITLE
Remove Service Wrapper now that Device SDK has same interface

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-rfid-llrp-go#102]
# 🚀 Tech Debt

### Relevant Package [**REQUIRED**]

 This feature request is for Driver

### Description [**REQUIRED**]
 A clear and concise description of the problem or missing capability...
Code here is no longer needed now that it is in the Device SDK
https://github.com/edgexfoundry/device-rfid-llrp-go/blob/main/internal/driver/service.go#L16

### Describe the solution you'd like
Remove code and refactor usages to use the code from the SDK.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by marcpfuller** [comment]
This has been resolved in PR #104

**Comment by iain-anderson** [comment]
closed #104
