### ISSUE TITLE
Making internal/llrp exported

### ISSUE THREAD

**Issue by dvcorreia** [edgexfoundry/device-rfid-llrp-go#291]
Would you consider making `internal/llrp` an exported package?

I would consider it the reference implementation of LLRP in go.
https://github.com/iomz/go-llrp has been unmaintained for a while.

**Comment by cloudxxx8** [comment]
this device service is the reference implementation, and we also don't have the resource to maintain the llrp driver logic

**Comment by dvcorreia** [comment]
I am fine with the driver being an internal package, it's very edgex specific and I understand the rational of keeping this way.
I think the `llrp` package being accessible is enough for anyone wanting to build a driver for themselves.

**Comment by cloudxxx8** [comment]
please feel free to open a refactor PR and move it out from internal
