### ISSUE TITLE
Service registry failures...

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-rfid-llrp-go#36]
While reviewing a [new PR](https://github.com/edgexfoundry/device-rfid-llrp-go/pull/35) for triggering discovery when config changes I ran into the following problem while testing.

When I build the latest version of device-rfid-llrp and run it against the latest/stable edgexfoundry snap, the device service is reporting that it cannot register to the registry because service information is not set.

Steps to reproduce:

1) Install edgexfoundry from latest/stable channel (i.e. Hanoi)

`    $ sudo snap install edgexfoundry
`

2) Build this device service (note, it seems this service has already been updated to use go 1.16 even though it hasn't been fully updated to use V2 yet).

3) Run the service:

```
$ ./cmd/device-rfid-llrp-go --cp=consul.http://localhost:8500 --registry --confdir=./cmd/res
level=INFO ts=2021-06-15T17:37:57.568201468Z app=edgex-device-rfid-llrp source=config.go:193 msg="Loaded configuration from ./cmd/res/configuration.toml"
level=INFO ts=2021-06-15T17:37:57.569435976Z app=edgex-device-rfid-llrp source=config.go:168 msg="Using Configuration provider (consul) from: http://localhost:8500 with base path of edgex/devices/1.0/edgex-device-rfid-llrp"
level=INFO ts=2021-06-15T17:37:57.661931575Z app=edgex-device-rfid-llrp source=config.go:304 msg="Configuration has been pushed to into Configuration Provider (0 envVars overrides applied)"
level=INFO ts=2021-06-15T17:37:57.66202106Z app=edgex-device-rfid-llrp source=registry.go:80 msg="Using Registry (consul) from http://localhost:8500"
level=WARN ts=2021-06-15T17:37:57.662972521Z app=edgex-device-rfid-llrp source=registry.go:140 msg="could not register service with Registry: unable to register service with consul: Service information not set"
level=WARN ts=2021-06-15T17:37:58.665509302Z app=edgex-device-rfid-llrp source=registry.go:140 msg="could not register service with Registry: unable to register service with consul: Service information not set"
level=WARN ts=2021-06-15T17:37:59.667690141Z app=edgex-device-rfid-llrp source=registry.go:140 msg="could not register service with Registry: unable to register service with consul: Service information not set"
level=WARN ts=2021-06-15T17:38:00.669953378Z app=edgex-device-rfid-llrp source=registry.go:140 msg="could not register service with Registry: unable to register service with consul: Service information not set"
^Clevel=WARN ts=2021-06-15T17:38:01.672800492Z app=edgex-device-rfid-llrp source=registry.go:140 msg="could not register service with Registry: unable to register service with consul: Service information not set"
level=ERROR ts=2021-06-15T17:38:01.672854758Z app=edgex-device-rfid-llrp source=bootstrap.go:45 msg="aborted RegisterWithRegistry()"
```

**Comment by tonyespy** [comment]
According to @lenny-intel, this error comes from this code in go-mod-registry:

That error comes from here: https://github.com/edgexfoundry/go-mod-registry/blob/f0ab76939e05a341cddab2856861b590de3bce1f/internal/pkg/consul/client.go#L93-L95

One of there is not set:
`client.serviceKey == "" || client.serviceAddress == "" || client.servicePort == 0 ||		client.healthCheckRoute == "" || client.healthCheckInterval == ""`

**Comment by ajcasagrande** [comment]
@tonyespy I noticed that too. I think it is one of the healthcheck values. I looked around at various other EdgeX device services and had trouble finding where they are setting those values. @lenny-intel Do you have a good example working service I can model from for these values?

**Comment by tonyespy** [comment]
@ajcasagrande I'm looking at this now, and will let you know what I find out.

**Comment by tonyespy** [comment]
It looks like `cmd/res/configuration.toml` is missing `Service.CheckInterval`.

**Comment by lenny-intel** [comment]
This is how we have it set in ASC:
https://github.com/edgexfoundry/app-service-configurable/blob/hanoi/res/rules-engine/configuration.toml#L20
