### ISSUE TITLE
Clean up READMe

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/device-rfid-llrp-go#53]
Clean up main repository README.md

- reference to holding repo for LLRP app service
- Reference older version APIs in Swagger

**Comment by lenny-intel** [comment]
@jim, Will have Marc handle these updates as part of the V2 migration.

**Comment by lenny-intel** [comment]
Should point to 2.1 swagger

**Comment by lenny-intel** [comment]
@marcpfuller is this one addressed with all the work you have done?

**Comment by marcpfuller** [comment]
@lenny-intel, I went throught the readme ad I i saw that the readme was already pointing 2.1.0 for swagger. I will check with surajit tomorrow for clarification

**Comment by lenny-intel** [comment]
Naw, this was Jim White issue. See top description. I just checked and there is still one reference to the old holding repo. Please update to point to the proper repo. THX!

**Comment by marcpfuller** [comment]
I have updated the link app-rfid-llrp-inventory  that pointed to holding repo to point to the correct edgex repo
