### ISSUE TITLE
Tagging for v2

### ISSUE THREAD

**Issue by farshidtz** [edgexfoundry/device-rfid-llrp-go#63]
The latest tag is `v1.0.1-dev.7` but the development is now done towards or beyond v2. 

Shouldn't we have dev tags for v2 instead?

**Comment by lenny-intel** [comment]
Nice catch. yes the tagging needs to be tweaked to `v2.1.0-dev.x` for a Jakarta release.

**Comment by lenny-intel** [comment]
I escalated this to Devops

**Comment by lenny-intel** [comment]
@farshidtz , @siggiskulason , this tagging issue has been resolved by DevOps. Thank you for pointing this out.
https://github.com/edgexfoundry/device-rfid-llrp-go/releases/tag/v2.1.0-dev.1
https://github.com/edgexfoundry/app-rfid-llrp-inventory/releases/tag/v2.1.0-dev.1
