### ISSUE TITLE
Scripts are not working as mentioned in readme on "example-scripts" segment

### ISSUE THREAD

**Issue by surajitx-pal** [edgexfoundry/device-rfid-llrp-go#70]
Readme - https://github.com/edgexfoundry/device-rfid-llrp-go#example-scripts

Folder path " device-rfid-llrp-go/examples/
Script files - command.sh, example.sh, data.sh

Issue: 
Script files - example.sh, command.sh, data.sh -  mainly used for Add/enable/Disable/Delete RO Sepc - and check device config and capabilities, read data  etc.

This files are not executing due json tags name are changed. command to check all supported device commands are available-           "curl  http://0.0.0.0:59882/api/v2/device/all | jq ."

![Screenshot from 2022-04-06 16-48-55](https://user-images.githubusercontent.com/80838686/162095670-cb67c790-3ea5-4006-902d-83ddf49961d2.png)

**Comment by marcpfuller** [comment]
I have updated the scripts in examples to work with the recent changes in edgex for devices-rfid-llrp and app-rfid-llrp

**Comment by marcpfuller** [comment]
This has been resolved
