### ISSUE TITLE
Failed DEBUG - message from device-rfid-llrp service while tag reading and DEBUG mode log setting in consul.

### ISSUE THREAD

**Issue by surajitx-pal** [edgexfoundry/device-rfid-llrp-go#71]
Consul mode - set logging mode "DEBUG"
Start tag reading after device discovery - below the failed log message.

edgex-device-rfid-llrp     | level=DEBUG ts=2022-04-06T23:26:58.797373245Z app=device-rfid-llrp source=transform.go:96 msg="failed to read ResourceOperation: failed to find ResourceOpertaion with DeviceResource ROAccessReport in Profile LLRP-Impinj-Profile" 
In DEBUG logging mode - this failed msg keep logging in console at start reading from app service.

**Comment by lenny-intel** [comment]
@surajitx-pal , how are your doing "Start tag reading after device discovery"?

**Comment by surajitx-pal** [comment]
@lenny-intel - Tag reading is working good after device discovery.

**Comment by lenny-intel** [comment]
@surajitx-pal , great! So you can close this issue?

**Comment by surajitx-pal** [comment]
@lenny-intel  - Yes, this is debug console message - logically we can close this issue.

**Comment by surajitx-pal** [comment]
This is debug mode console message - but tags reading are working good, this is not an issue.
