### ISSUE TITLE
'AddROSpec' - this command not available for llrp device service 

### ISSUE THREAD

**Issue by surajitx-pal** [edgexfoundry/device-rfid-llrp-go#72]
This below command to check all available commands for core-command service but "AddROSpec" not available. 
curl  http://0.0.0.0:59882/api/v2/device/name/SpeedwayR-11-43-62 | jq '.deviceCoreCommand | .coreCommands[].name'

![Screenshot from 2022-04-06 15-32-53](https://user-images.githubusercontent.com/80838686/162096361-9c4c4636-d038-4e70-b3c6-7a449193a7e0.png)

![Screenshot from 2022-04-06 17-26-53](https://user-images.githubusercontent.com/80838686/162096481-0154f070-d9f8-4de7-8b7e-0822214a84f4.png)

**Comment by surajitx-pal** [comment]
> core-command

p device

**Comment by surajitx-pal** [comment]
NOTE: curl -so- -X PUT http://0.0.0.0:59882/api/v2/device/name/SpeedwayR-11-43-62/enableROSpec 'Content-Type: application/json' --data '{ "ROSpecID": 1 }'   
 this command is return success but no such start reading/no reading led blinking at impinj device etc.

**Comment by lenny-intel** [comment]
> NOTE: curl -so- -X PUT http://0.0.0.0:59882/api/v2/device/name/SpeedwayR-11-43-62/enableROSpec 'Content-Type: application/json' --data '{ "ROSpecID": 1 }' this command is return success but no such start reading/no reading led blinking at impinj device etc.

@surajitx-pal , what do the log files for Command and LLRP device service show when Debug logging is on?

**Comment by surajitx-pal** [comment]
@lenny-intel - Now enableROSpec command direct start reading the tags, Here is the console logs is attached.  but some failed log message also. please review-
![Screenshot from 2022-04-11 15-34-41](https://user-images.githubusercontent.com/80838686/162844367-b587bd39-861a-4b6c-93f6-444b2cf79434.png)
![Screenshot from 2022-04-11 15-34-26](https://user-images.githubusercontent.com/80838686/162844371-fb8610ab-6ec4-41b6-a73b-94ce5bc375b8.png)

**Comment by surajitx-pal** [comment]
Need to update read-me doc, AddROSpec part also.
https://github.com/edgexfoundry/device-rfid-llrp-go#device-profiles-custom-llrp-messages-and-service-limitations

**Comment by lenny-intel** [comment]
@surajitx-pal , this issue can not be closed, correct. 

@marcpfuller did you address this: 
> Need to update read-me doc, AddROSpec part also.
> https://github.com/edgexfoundry/device-rfid-llrp-go#device-profiles-custom-llrp-messages-and-service-limitations

**Comment by surajitx-pal** [comment]
'AddROSpec'  this API is changed to ROSpec, and Read-me is updated. and working with Example scripts.
